spring.application.name=JavaSpringUsers
server.port=8081

# H2 in-memory
spring.datasource.url=jdbc:h2:mem:users_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Configuration JWT (Itération 5)
jwt.secret=MaSuperCleSecreteDe256BitsPourSignerMesTokensEnTouteSecurite!
jwt.expiration=86400000

